[package]
authors = ["49nord GmbH <hello@49nord.de>"]
description = "Guard a process by terminating it on drop"
documentation = "https://docs.rs/process_guard"
license = "MIT OR Apache-2.0"
name = "process_guard"
readme = "README.md"
repository = "https://github.com/49nord/process_guard-rs"
version = "0.3.0"
edition = "2024"
rust-version = "1.85"

[dependencies]
log = "0.4.33"
nix = { version = "0.31.3", features = ["signal"] }
thiserror = "2.0.20"
